# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImportExport.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 50, 231, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 110, 88, 34))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 190, 231, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 50, 41, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 190, 41, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 240, 88, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 30))
        self.menubar.setObjectName("menubar")
        self.menuPr_r_glages = QtWidgets.QMenu(self.menubar)
        self.menuPr_r_glages.setObjectName("menuPr_r_glages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionP1 = QtWidgets.QAction(MainWindow)
        self.actionP1.setObjectName("actionP1")
        self.actionP2 = QtWidgets.QAction(MainWindow)
        self.actionP2.setObjectName("actionP2")
        self.actionP3 = QtWidgets.QAction(MainWindow)
        self.actionP3.setObjectName("actionP3")
        self.actionP4 = QtWidgets.QAction(MainWindow)
        self.actionP4.setObjectName("actionP4")
        self.actionP5 = QtWidgets.QAction(MainWindow)
        self.actionP5.setObjectName("actionP5")
        self.menuPr_r_glages.addAction(self.actionP1)
        self.menuPr_r_glages.addAction(self.actionP2)
        self.menuPr_r_glages.addAction(self.actionP3)
        self.menuPr_r_glages.addAction(self.actionP4)
        self.menuPr_r_glages.addAction(self.actionP5)
        self.menubar.addAction(self.menuPr_r_glages.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tobias\'s Import Export Page"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Chemin Source"))
        self.pushButton.setText(_translate("MainWindow", "Inverser"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Chemin de Destination"))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.pushButton_3.setText(_translate("MainWindow", "..."))
        self.pushButton_4.setText(_translate("MainWindow", "Process"))
        self.menuPr_r_glages.setTitle(_translate("MainWindow", "Préréglages"))
        self.actionP1.setText(_translate("MainWindow", "P1"))
        self.actionP2.setText(_translate("MainWindow", "P2"))
        self.actionP3.setText(_translate("MainWindow", "P3"))
        self.actionP4.setText(_translate("MainWindow", "P4"))
        self.actionP5.setText(_translate("MainWindow", "P5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
