# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtFiles/BlocNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 0, 411, 491))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 431, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuParam_tres = QtWidgets.QMenu(self.menuBar)
        self.menuParam_tres.setObjectName("menuParam_tres")
        self.menuSauvegarder = QtWidgets.QMenu(self.menuBar)
        self.menuSauvegarder.setObjectName("menuSauvegarder")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionSauvegarder = QtWidgets.QAction(MainWindow)
        self.actionSauvegarder.setObjectName("actionSauvegarder")
        self.actionNouvelles_Notes = QtWidgets.QAction(MainWindow)
        self.actionNouvelles_Notes.setObjectName("actionNouvelles_Notes")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuParam_tres.addAction(self.actionNouvelles_Notes)
        self.menuParam_tres.addAction(self.actionOpen)
        self.menuSauvegarder.addAction(self.actionSave)
        self.menuBar.addAction(self.menuParam_tres.menuAction())
        self.menuBar.addAction(self.menuSauvegarder.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tobias\'s Bloc Note"))
        self.menuParam_tres.setTitle(_translate("MainWindow", "Ouvrir"))
        self.menuSauvegarder.setTitle(_translate("MainWindow", "Sauvegarder"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionSauvegarder.setText(_translate("MainWindow", "Sauvegarder"))
        self.actionNouvelles_Notes.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
