# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageServeur.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 110, 351, 231))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 20, 161, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 181, 18))
        self.label.setObjectName("label")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(550, 150, 351, 151))
        self.listWidget_2.setObjectName("listWidget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 410, 351, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 20, 161, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 130, 181, 18))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(550, 310, 351, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 370, 71, 34))
        self.pushButton.setObjectName("pushButton")
        self.listWidget_3 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_3.setGeometry(QtCore.QRect(550, 30, 351, 81))
        self.listWidget_3.setObjectName("listWidget_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 10, 181, 18))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 410, 81, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 360, 351, 32))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(390, 360, 81, 32))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 30))
        self.menubar.setObjectName("menubar")
        self.menuMTP = QtWidgets.QMenu(self.menubar)
        self.menuMTP.setObjectName("menuMTP")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMulti_Task_Pc = QtWidgets.QAction(MainWindow)
        self.actionMulti_Task_Pc.setObjectName("actionMulti_Task_Pc")
        self.menuMTP.addAction(self.actionMulti_Task_Pc)
        self.menubar.addAction(self.menuMTP.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tobias\'s Serv Page"))
        self.pushButton_2.setText(_translate("MainWindow", "Créer une commande"))
        self.label.setText(_translate("MainWindow", "Liste d\'ordinateurs éligibles"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Mot de passe"))
        self.pushButton_3.setText(_translate("MainWindow", "Rajouter un ordinateur"))
        self.label_3.setText(_translate("MainWindow", "Liste de commandes crées"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Commande à réaliser"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.label_4.setText(_translate("MainWindow", "Sujets d\'exécution"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Save"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Don\'t Save"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Nom d\'utilisateur"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Save"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Don\'t Save"))
        self.menuMTP.setTitle(_translate("MainWindow", "MTP"))
        self.actionMulti_Task_Pc.setText(_translate("MainWindow", "Multi Task/Pc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
